var data =[{"author":"Codee","book_name":"Squirrel, arctic ground","pages":33,"year":1987},
{"author":"Roman","book_name":"Tortoise, radiated","pages":40,"year":2000},
{"author":"Tull","book_name":"Caiman, spectacled","pages":12,"year":2010},
{"author":"Merola","book_name":"Polecat, african","pages":26,"year":2005},
{"author":"Terrell","book_name":"European shelduck","pages":94,"year":2011},
{"author":"Bryn","book_name":"Cape white-eye","pages":80,"year":1998},
{"author":"Annmaria","book_name":"Large cormorant","pages":52,"year":2007},
{"author":"Rocky","book_name":"Wallaby, tammar","pages":36,"year":2004},
{"author":"Dare","book_name":"Indian star tortoise","pages":87,"year":2008},
{"author":"Percy","book_name":"Goose, knob-nosed","pages":47,"year":1987},
{"author":"Marna","book_name":"Pie, indian tree","pages":59,"year":2000},
{"author":"Shea","book_name":"Red-necked phalarope","pages":11,"year":1984},
{"author":"Rosetta","book_name":"Black and white colobus","pages":6,"year":2008},
{"author":"Susy","book_name":"Possum, western pygmy","pages":15,"year":2006},
{"author":"Dreddy","book_name":"Little grebe","pages":75,"year":2006},
{"author":"Rebekkah","book_name":"Eland, common","pages":4,"year":2005},
{"author":"Denni","book_name":"King vulture","pages":84,"year":1993},
{"author":"Elwyn","book_name":"Bonnet macaque","pages":5,"year":1996},
{"author":"Jonathon","book_name":"Turkey vulture","pages":27,"year":2009},
{"author":"Elna","book_name":"Buffalo, african","pages":81,"year":1994},
{"author":"Dora","book_name":"Fisher","pages":73,"year":2012},
{"author":"Emmett","book_name":"Owl, snowy","pages":80,"year":2011},
{"author":"Flory","book_name":"Western lowland gorilla","pages":41,"year":1992},
{"author":"Dominica","book_name":"Great kiskadee","pages":78,"year":2010},
{"author":"Florinda","book_name":"Armadillo, nine-banded","pages":44,"year":2011},
{"author":"Wynne","book_name":"Crown of thorns starfish","pages":81,"year":1995},
{"author":"Guss","book_name":"Albatross, waved","pages":80,"year":1995},
{"author":"Gena","book_name":"Blacksmith plover","pages":29,"year":1996},
{"author":"Abagael","book_name":"Pied kingfisher","pages":51,"year":2010},
{"author":"Lowe","book_name":"Slender-billed cockatoo","pages":12,"year":2010},
{"author":"Pebrook","book_name":"Red-winged hawk (unidentified)","pages":28,"year":2001},
{"author":"Jo-anne","book_name":"Bat, little brown","pages":12,"year":1991},
{"author":"Padraic","book_name":"Oystercatcher, blackish","pages":98,"year":2007},
{"author":"Hillier","book_name":"Green-winged trumpeter","pages":45,"year":2011},
{"author":"Alan","book_name":"Dove, little brown","pages":75,"year":1997},
{"author":"Kenn","book_name":"Fox, pampa gray","pages":56,"year":2009},
{"author":"Ganny","book_name":"Gecko, tokay","pages":59,"year":2007},
{"author":"Marvin","book_name":"White-nosed coatimundi","pages":71,"year":1997},
{"author":"Mattias","book_name":"Gaur","pages":43,"year":2000},
{"author":"Reade","book_name":"Thrasher, curve-billed","pages":12,"year":2002},
{"author":"Marj","book_name":"Barbet, black-collared","pages":6,"year":1992},
{"author":"Marcelia","book_name":"Peccary, collared","pages":75,"year":2001},
{"author":"Stepha","book_name":"Black-crowned crane","pages":27,"year":1996},
{"author":"Layla","book_name":"Skunk, striped","pages":27,"year":2010},
{"author":"Nerty","book_name":"Quail, gambel's","pages":92,"year":2011},
{"author":"Johnathon","book_name":"Lion, asian","pages":75,"year":1984},
{"author":"Shayla","book_name":"Kinkajou","pages":77,"year":1978},
{"author":"Carmencita","book_name":"Eastern grey kangaroo","pages":30,"year":2001},
{"author":"Francyne","book_name":"Gecko, ring-tailed","pages":69,"year":2011},
{"author":"Brandy","book_name":"Spotted wood sandpiper","pages":5,"year":1996},
{"author":"Gustave","book_name":"Asian water dragon","pages":86,"year":1991},
{"author":"Grange","book_name":"Grison","pages":77,"year":1999},
{"author":"Theobald","book_name":"Phalarope, red","pages":37,"year":1990},
{"author":"Iormina","book_name":"Goose, andean","pages":65,"year":2012},
{"author":"Marve","book_name":"Macaque, rhesus","pages":12,"year":2001},
{"author":"Pia","book_name":"Wagtail, african pied","pages":73,"year":1993},
{"author":"Edmon","book_name":"Southern black-backed gull","pages":52,"year":2000},
{"author":"Hiram","book_name":"Small Indian mongoose","pages":59,"year":2009},
{"author":"Zsa zsa","book_name":"Kangaroo, eastern grey","pages":15,"year":1994},
{"author":"Roxi","book_name":"Zorro, common","pages":43,"year":2002},
{"author":"Kelley","book_name":"Godwit, hudsonian","pages":3,"year":2000},
{"author":"Barbey","book_name":"Large cormorant","pages":27,"year":1996},
{"author":"Woody","book_name":"Puma","pages":86,"year":2007},
{"author":"Crichton","book_name":"Gorilla, western lowland","pages":18,"year":1998},
{"author":"Ken","book_name":"Dama wallaby","pages":93,"year":2000},
{"author":"Maurine","book_name":"Rhinoceros, square-lipped","pages":9,"year":2002},
{"author":"Cord","book_name":"Black-crowned crane","pages":59,"year":2010},
{"author":"Julienne","book_name":"Starling, red-shouldered glossy","pages":85,"year":1998},
{"author":"Cele","book_name":"Bushbuck","pages":85,"year":2006},
{"author":"Denny","book_name":"Vulture, griffon","pages":66,"year":1994},
{"author":"Malorie","book_name":"Snake-necked turtle","pages":100,"year":1991},
{"author":"Ki","book_name":"Steenbuck","pages":89,"year":2012},
{"author":"Quintana","book_name":"South American puma","pages":42,"year":2011},
{"author":"Vladamir","book_name":"Komodo dragon","pages":82,"year":1993},
{"author":"Corette","book_name":"Peccary, collared","pages":99,"year":2002},
{"author":"Dareen","book_name":"Penguin, magellanic","pages":95,"year":2010},
{"author":"Bob","book_name":"Caracara, yellow-headed","pages":27,"year":2002},
{"author":"Elise","book_name":"Spoonbill, european","pages":24,"year":2012},
{"author":"Bambie","book_name":"Tortoise, radiated","pages":44,"year":2011},
{"author":"Yovonnda","book_name":"Mongoose, yellow","pages":92,"year":1995},
{"author":"Vachel","book_name":"Barrows goldeneye","pages":52,"year":2011},
{"author":"Letitia","book_name":"Red squirrel","pages":71,"year":1992},
{"author":"Hakim","book_name":"Cormorant, great","pages":30,"year":2000},
{"author":"Chrotoem","book_name":"Brush-tailed bettong","pages":49,"year":1985},
{"author":"Roze","book_name":"Carpet snake","pages":73,"year":2013},
{"author":"Seth","book_name":"Bandicoot, short-nosed","pages":39,"year":1998},
{"author":"Jorie","book_name":"Lion, asian","pages":92,"year":2005},
{"author":"Nefen","book_name":"Macaque, rhesus","pages":39,"year":2006},
{"author":"Etheline","book_name":"White-cheeked pintail","pages":53,"year":1995},
{"author":"Diena","book_name":"Crowned eagle","pages":24,"year":2005},
{"author":"Lana","book_name":"Russian dragonfly","pages":40,"year":1996},
{"author":"Reidar","book_name":"Gemsbok","pages":14,"year":2007},
{"author":"Euell","book_name":"Malabar squirrel","pages":40,"year":2006},
{"author":"Joyous","book_name":"Fork-tailed drongo","pages":64,"year":1983},
{"author":"Lothario","book_name":"Indian star tortoise","pages":68,"year":2009},
{"author":"Enrika","book_name":"Long-tailed skua","pages":56,"year":2011},
{"author":"Magda","book_name":"Steenbuck","pages":12,"year":2006},
{"author":"Margareta","book_name":"Giant anteater","pages":42,"year":2001},
{"author":"Deane","book_name":"Hummingbird (unidentified)","pages":55,"year":2002},
{"author":"Rodger","book_name":"White-mantled colobus","pages":41,"year":1986}]

module.exports = data